class MyClass
    fn Test()
        try
            DoThing()
        catch
            ; whee
        catch Exception
            ; whee
        catch Exception ex
            ; whee
        fin
            Print("done")
