class MyClass
    fn Test()
        throw new Exception("oh no")
